os:
  - linux
  - osx
sudo: false
dist: trusty
language: node_js
node_js:
  - '6.5.0'
before_script:
  - yarn add --dev coveralls
script:
  - npm run lint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm test; fi
  - npm run build
after_success:
  - npm run package
cache:
  yarn: true
  directories:
    - $HOME/.electron
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
