language: node_js
node_js:
  - '6'
before_script:
  - yarn add --dev coveralls
script:
  - npm run lint
  - npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - npm run test-storybook
cache: yarn
