os:
  - linux
  - osx
sudo: false
dist: trusty
language: node_js
node_js:
  - '6'
before_script:
  - yarn add --dev coveralls
script:
  - npm run lint
  - npm run test-storybook &&
    npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls &&
    npm run build
after_success:
  - npm run package
cache:
  yarn: true
  directories:
    - $HOME/.electron
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
